import {createHash,randomBytes} from 'node:crypto';import type {Pool,PoolClient} from 'pg';import {z} from 'zod'
import {hostingPool} from '../../deploy/postgres';import {requireCloudRole} from '../authorization';import {CloudError,type CloudContext} from '../types';import {hashToken} from '../oidc';import {CLOUD_ORIGINS} from '../origins';import {readBytes} from '../http';import {sealCredentials,openCredentials} from './credentials'
function configuration(){const origin=process.env.CLOUD_ORIGIN??'https://cloud.axxes.app';const clientId=process.env.CLOUD_GITHUB_CLIENT_ID,clientSecret=process.env.CLOUD_GITHUB_CLIENT_SECRET,key=process.env.CLOUD_GITHUB_TOKEN_ENCRYPTION_KEY;if(!CLOUD_ORIGINS.includes(origin as typeof CLOUD_ORIGINS[number])||!clientId||!clientSecret||!key)throw new CloudError('github_not_configured',503);return {origin,clientId,clientSecret,key}}
export async function beginGithub(ctx:CloudContext,connection:Pool|PoolClient=hostingPool()){
 requireCloudRole(ctx,'admin');const config=configuration();const state=randomBytes(32).toString('base64url');const verifier=randomBytes(32).toString('base64url');await connection.query("INSERT INTO cloud_github_transactions(state_hash,user_id,tenant_id,verifier,expires_at) VALUES($1,$2,$3,$4,statement_timestamp()+interval '5 minutes')",[hashToken(state),ctx.userId,ctx.tenant.id,verifier]);const url=new URL('https://github.com/login/oauth/authorize');url.searchParams.set('client_id',config.clientId);url.searchParams.set('redirect_uri',config.origin+'/api/cloud/github/callback');url.searchParams.set('state',state);url.searchParams.set('code_challenge',createHash('sha256').update(verifier).digest('base64url'));url.searchParams.set('code_challenge_method','S256');return {state,url:url.href}
}
export async function finishGithub(ctx:CloudContext,state:string,code:string,connection:Pool|PoolClient=hostingPool(),fetcher:typeof fetch=fetch){
 requireCloudRole(ctx,'admin');const config=configuration();z.string().min(1).max(2048).parse(code)
 const claimed=await connection.query('UPDATE cloud_github_transactions SET used_at=statement_timestamp() WHERE state_hash=$1 AND user_id=$2 AND tenant_id=$3 AND used_at IS NULL AND expires_at>statement_timestamp() RETURNING verifier',[hashToken(state),ctx.userId,ctx.tenant.id]);if(claimed.rowCount!==1)throw new CloudError('github_transaction_expired',401)
 const response=await fetcher('https://github.com/login/oauth/access_token',{method:'POST',headers:{accept:'application/json','content-type':'application/json'},body:JSON.stringify({client_id:config.clientId,client_secret:config.clientSecret,code,code_verifier:claimed.rows[0].verifier,redirect_uri:config.origin+'/api/cloud/github/callback'}),redirect:'error',signal:AbortSignal.timeout(15000),cache:'no-store'});if(!response.ok)throw new CloudError('github_exchange_failed',401);const data=JSON.parse((await readBytes(response.body,65536,15000)).toString('utf8'));if(typeof data.access_token!=='string'||!data.access_token)throw new CloudError('github_exchange_failed',401)
 const expires=Number.isSafeInteger(data.expires_in)&&data.expires_in>0?Math.min(data.expires_in,28800):3600;const encrypted=sealCredentials({accessToken:data.access_token,...(typeof data.refresh_token==='string'?{refreshToken:data.refresh_token}:{})},ctx.tenant.id+':'+ctx.userId,config.key)
 await connection.query('INSERT INTO cloud_github_connections(tenant_id,user_id,encrypted_credentials,expires_at) VALUES($1,$2,$3,statement_timestamp()+($4::int*interval \'1 second\')) ON CONFLICT(tenant_id,user_id) DO UPDATE SET encrypted_credentials=EXCLUDED.encrypted_credentials,expires_at=EXCLUDED.expires_at',[ctx.tenant.id,ctx.userId,encrypted,expires]);return {connected:true}
}
export async function githubUserToken(ctx:CloudContext,connection:Pool|PoolClient=hostingPool()){
 const config=configuration();const r=await connection.query('SELECT encrypted_credentials FROM cloud_github_connections WHERE tenant_id=$1 AND user_id=$2 AND expires_at>statement_timestamp()',[ctx.tenant.id,ctx.userId]);if(r.rowCount!==1)throw new CloudError('github_reconnect_required',401);return openCredentials(r.rows[0].encrypted_credentials,ctx.tenant.id+':'+ctx.userId,config.key).accessToken
}
