import type {Pool,PoolClient} from 'pg';import {z} from 'zod';import {hostingPool} from '../../deploy/postgres';import {verifyRepositoryAccess} from '../../deploy/github/access';import {readBytes} from '../http';import {CloudError,type CloudContext} from '../types';import {githubJson,installationToken} from './client';import {githubUserToken} from './oauth';import {extractGitHubArchive} from './archive'
export type SourceBinding={installationId:number;repositoryId:number;branch:string}
export async function sourceFiles(ctx:CloudContext,binding:SourceBinding,commitSha:string,connection:Pool|PoolClient=hostingPool(),fetcher:typeof fetch=fetch){
 z.string().regex(/^[a-f0-9]{40}$/).parse(commitSha);const installationId=z.number().int().positive().safe().parse(binding.installationId),repositoryId=z.number().int().positive().safe().parse(binding.repositoryId);z.string().min(1).max(1013).parse(binding.branch)
 const userToken=await githubUserToken(ctx,connection);const verified=await verifyRepositoryAccess(ctx,installationId,repositoryId,async path=>{const response=await fetcher('https://api.github.com'+path,{headers:{authorization:'Bearer '+userToken,accept:'application/vnd.github+json','x-github-api-version':'2026-03-10'},redirect:'error',signal:AbortSignal.timeout(15000),cache:'no-store'});if(!response.ok)throw new CloudError('repository_access_revoked',403);return JSON.parse((await readBytes(response.body,1024*1024,15000)).toString('utf8'))})
 const token=await installationToken(installationId,repositoryId,fetcher);const head=await githubJson('/repos/'+verified.fullName+'/commits/'+encodeURIComponent(binding.branch),token,undefined,fetcher);z.string().regex(/^[a-f0-9]{40}$/).parse(head.sha)
 if(head.sha!==commitSha){const comparison=await githubJson('/repos/'+verified.fullName+'/compare/'+commitSha+'...'+head.sha,token,undefined,fetcher);if(!['ahead','identical'].includes(comparison.status))throw new CloudError('commit_not_on_bound_branch',403)}
 let response=await fetcher('https://api.github.com/repos/'+verified.fullName+'/tarball/'+commitSha,{headers:{authorization:'Bearer '+token,accept:'application/vnd.github+json','x-github-api-version':'2026-03-10'},redirect:'manual',signal:AbortSignal.timeout(30000),cache:'no-store'})
 if([301,302,307,308].includes(response.status)){const location=response.headers.get('location');if(!location)throw new CloudError('source_rejected');const target=new URL(location);if(target.protocol!=='https:'||target.hostname!=='codeload.github.com'||target.port||target.username||target.password)throw new CloudError('source_redirect_rejected');response=await fetcher(target,{redirect:'error',signal:AbortSignal.timeout(30000),cache:'no-store'})}
 if(!response.ok)throw new CloudError('source_download_failed',403);const archive=await readBytes(response.body,50*1024*1024,30000);return extractGitHubArchive(archive)
}
