'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
type Key={id:string;name:string;scopes:string[];expires_at:string;revoked_at:string|null}
export function ApiKeys({keys}:{keys:Key[]}){
 const router=useRouter(),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[token,setToken]=useState('')
 async function request(path:string,body:unknown){const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error??'request_failed');return data}
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setToken('');try{const data=await request('/api/cloud/keys',{name,scopes:['read'],days:30});if(!data.key?.token)throw Error('key_creation_failed');setToken(data.key.token);setName('');router.refresh()}catch(e){setError(e instanceof Error?e.message:'request_failed')}finally{setBusy(false)}}
 async function revoke(key:Key){if(!window.confirm('Revoke “'+key.name+'”? Requests using it will stop working.'))return;setBusy(true);setError('');try{await request('/api/cloud/keys/revoke',{id:key.id});setToken('');router.refresh()}catch(e){setError(e instanceof Error?e.message:'request_failed')}finally{setBusy(false)}}
 return <section className="card space-y-4 p-5"><h2 className="font-semibold">API credentials</h2><p className="text-sm text-muted">Read your organization’s projects, apps and activity from scripts. Credentials expire after 30 days.</p><form onSubmit={create} className="flex flex-wrap items-end gap-3"><label className="flex-1 text-sm">Credential name<input className="input mt-2" value={name} onChange={e=>setName(e.target.value)} maxLength={80} required/></label><button className="btn-primary" disabled={busy||!name.trim()}>Create read credential</button></form>{token&&<div className="space-y-2"><p className="text-sm">Copy this credential now. It is shown only once.</p><input aria-label="New API credential" className="input font-mono text-xs" readOnly value={token} onFocus={e=>e.currentTarget.select()}/><button className="text-sm text-accent" onClick={()=>{setToken('')}}>I’ve saved it</button></div>}{error&&<p role="alert" className="text-sm text-danger">{error.replaceAll('_',' ')}</p>}{keys.length?<ul className="divide-y divide-line">{keys.map(k=><li key={k.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-medium">{k.name}</p><p className="text-xs text-muted">{k.revoked_at?'Revoked':'Expires '+new Date(k.expires_at).toLocaleDateString()}</p></div>{!k.revoked_at&&<button className="text-sm text-danger" disabled={busy} onClick={()=>void revoke(k)}>Revoke</button>}</li>)}</ul>:<p className="text-sm text-muted">No credentials yet.</p>}<p className="text-xs text-muted">Send your credential as a Bearer token to <code>/api/cloud/projects</code>, <code>/api/cloud/resources</code> or <code>/api/cloud/jobs</code>.</p></section>
}
