'use client'
import {useState} from 'react';import {useRouter} from 'next/navigation'
export function ProjectForm(){const [name,setName]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const router=useRouter()
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const res=await fetch('/api/cloud/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name})});const data=await res.json();if(!res.ok)throw Error(data.error??'project_creation_failed');if(!data.project?.id)throw Error('project_creation_failed');setName('');router.refresh()}catch(e){setError(e instanceof Error?e.message:'project_creation_failed')}finally{setBusy(false)}}
 return <form onSubmit={submit} className="card space-y-3 p-5"><label className="block text-sm font-medium">New project<input value={name} onChange={e=>setName(e.target.value)} className="input mt-2" placeholder="Website or application" maxLength={80} required/></label>{error&&<p role="alert" className="text-sm text-danger">{error.replaceAll('_',' ')}</p>}<button disabled={busy||!name.trim()} className="btn-primary">{busy?'Creating…':'Create project'}</button></form>
}
export function CloudOrganization({memberships,selected}:{memberships:{tenantId:string;name:string}[];selected:string}){const router=useRouter();const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 async function switchTo(tenantId:string){setBusy(true);setError('');try{const res=await fetch('/api/cloud/organization',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tenantId})});if(!res.ok)throw Error('Could not switch organization');router.refresh()}catch{setError('Could not switch organization')}finally{setBusy(false)}}
 return <div><label className="block text-xs text-muted">Organization<select className="input mt-1 w-full" aria-label="Organization" value={selected} disabled={busy} onChange={e=>void switchTo(e.target.value)}>{memberships.map(m=><option key={m.tenantId} value={m.tenantId}>{m.name}</option>)}</select></label>{error&&<p role="alert" className="mt-2 text-xs text-danger">{error}</p>}</div>
}
export function CloudSignOut(){const [error,setError]=useState('');async function signOut(){try{const res=await fetch('/api/cloud/auth/sign-out',{method:'POST'});if(!res.ok)throw Error();window.location.assign('/cloud/sign-in')}catch{setError('Could not sign out')}}return <div><button className="text-sm text-muted hover:text-text" onClick={signOut}>Sign out</button>{error&&<p role="alert" className="text-xs text-danger">{error}</p>}</div>}
